CREATE TABLE IF NOT EXISTS seed_label_packages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  package_size_kg DECIMAL(10, 2) NOT NULL,
  labels_per_package INT NOT NULL DEFAULT 1,
  price_ugx INT NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
